### ISSUE TITLE
Not setting value of timeline tag

### ISSUE THREAD

**Issue by liamcain** [Darakah/obsidian-timelines#1]
https://github.com/Darakah/obsidian-timelines/blob/685dddb902b990085af34c94fe6170112daf1c8a/main.ts#L202

Since you're not setting the value here, the field won't get populated when the user restarts Obsidian.

Style-nit: you switch between camelCase, PascalCase, and snake_case a lot. Javascript and Typescript styleguides tend to prefer camelCase for all variable names and function names.

It's a lot safer to use string interpolation like this:

```ts
const someString = `my name is ${name}`;
```

rather than using +. + is weird in JS and you might unknowingly cast a string to a number.

https://github.com/Darakah/obsidian-timelines/blob/685dddb902b990085af34c94fe6170112daf1c8a/main.ts#L25
`_this` is unused.

https://github.com/Darakah/obsidian-timelines/blob/685dddb902b990085af34c94fe6170112daf1c8a/main.ts#L79-L82
I recommend using a code formatter since your indentation is often incorrect, making it hard to review.

https://github.com/Darakah/obsidian-timelines/blob/685dddb902b990085af34c94fe6170112daf1c8a/main.ts#L90
I don't think this works? `Number.isInteger("1")` returns false.

https://github.com/Darakah/obsidian-timelines/blob/685dddb902b990085af34c94fe6170112daf1c8a/main.ts#L122
When is this nullable? You probably want to filter instead otherwise the alternation logic won't work.

I really recommend against building the html with string concatenation since it's easy to make a mistake and it's hard to debug. Also, since you're using user data, it will need to be properly escaped - right now a user can't use `'` in their description.

**Comment by liamcain** [comment]
Oh, I see. You are parsing the string as a number by prepending it with a slash. It's probably easier just to validate the date with MomentJS (you can use `window.moment(formattedStr)` here) instead if you can make assumptions about how the date is formatted.

**Comment by Darakah** [comment]
I had replied on the pull request I thought you would see it there.

Yes, the date format is specified in the README and this is based on that assumption

**Comment by liamcain** [comment]
(keeping the conversation here since github only transcludes line numbers if its the current repo)

**Comment by Darakah** [comment]
Dear Liam, 

Just pushed version 0.1.1 to address all your remarks.

**_-> Style-nit:_** Adjusted all variable names to a single convention of  camelCase. Thank you for the remark.

**_-> string interpolation:_** As suggested, I replaced all string concatenations with the string interpolation to avoid any unwanted casting. 

**_-> Unused:_** deleted https://github.com/Darakah/obsidian-timelines/blob/685dddb902b990085af34c94fe6170112daf1c8a/main.ts#L25

**_-> code formatted:_** reformatted using VS Code and replaced all indentations to tabs.

**_-> Escaping possible breaking characters in user strings:_** Used regular expression to replace possible breaking characters.

**Comment by Darakah** [comment]
Great thanks for you helpful remarks and input. Much appreciated. 
Please let me know if anything else remains.

**Comment by Darakah** [comment]
Oh, i forgot to mention your first remark (I misunderstood your remark though you were asking me to remove it as it was not being used). I am setting the tag actually at this line:

https://github.com/Darakah/obsidian-timelines/blob/685dddb902b990085af34c94fe6170112daf1c8a/main.ts#L204

**Comment by liamcain** [comment]
> Oh, i forgot to mention your first remark (I misunderstood your remark thought you were asking me to remove it as it was not being used). I am setting the tag actually at this line:

That is within an onChange callback, so it won't run when the SettingTab is initialized. You'll need to call setValue outside the onchange as well.

Also, this is an issue for the setting below as well:

```ts
toggle.setValue(this.plugin.settings.DEFAULT_SORT_DIRECTION);
```

This means that every time the plugin is loaded, the setting will display the default value instead of the one configured by the user.

**Comment by Darakah** [comment]
Hey Liam, 

Thanks for your review. I however do not see this happening.

With the current version unchanged: 
- Go into settings -> you see default tag `timeline`
- Modify it to `test` -> exist settings
- Go back into settings -> still `test`
- Unload plugin -> Reload plugin -> go into settings still set to `test`

I used this same method with my other plugins as well and haven't encountered what you refer to. 

When a value is modified it is directly followed by https://github.com/Darakah/obsidian-timelines/blob/886d7d38387c17b5757c807de624e95cfe6fcf6b/main.ts#L215 the save settings which updates the data fields. 

and when a plugin is loaded it has to wait for those settings (saved by the user) to be loaded https://github.com/Darakah/obsidian-timelines/blob/886d7d38387c17b5757c807de624e95cfe6fcf6b/main.ts#L37

Did you test this out and were able to replicate this? Can you specify exactly what you did?

Many thanks for any feedback.

**Comment by liamcain** [comment]
### For default timeline tag:

Yes, I tested it, the existing value turns into the placeholder when you reopen the settings window (which I don't think you want). you are doing the correct thing with the the toggle below - Calling setValue inside the callback and outside the callback to initialize it.

### For Chronological Direction

I was confused because your setting is called "DEFAULT_SORT_DIRECTION." This is working fine, but the code would be more clear if you named this "sortDirection" because it's _not_ a constant value. In javascript and typescript, all caps variables usually denote properties and values that don't change for the duration of the program.

This might make it more clear:

```ts
const DEFAULT_SETTINGS: TimelinesSettings = {
	timelineTag: 'timeline',
	sortDirection: true
}
```

While the object above is the "default" settings, the properties themselves shouldn't have default_ in the name. They are the actual property names that the user will be updating.

**Comment by Darakah** [comment]
Agreed the naming is a confusing, will rename accordingly thanks for pointing that out.
As for the other issue i still can't replicate it.

**Comment by liamcain** [comment]
Sorry if I wasn't clear what I meant. Here's the behavior that I'm referring to:
![VWE0GVY6Kn](https://user-images.githubusercontent.com/693981/107299440-608be280-6a45-11eb-85b1-c54854da87e3.gif)

The saved value is getting set as the placeholder text. Instead, the saved value should be set using setValue, and the default value should be the placeholder. Something like:

 ```ts
			.addText(text => text
                                .setPlaceholder(DEFAULT_SETTINGS.timelineTag)
				.setValue(this.plugin.settings.timelineTag)
```

Does that make sense?

**Comment by Darakah** [comment]
Hey Liam, 

Thanks for the nice video. Yes, this is the behavior i intended for and it is needed for the following reason: 
User changes default tag `timeline` to something else -> time passes -> user forgets what the used tag is or wants to replace it -> thus to check the tag that is currently used to tag notes for pick-up he just opens the settings and can read it as the placeholder. 

I dont see any advantage on the other hand for keep the default tag `timeline` once it is changed. 

I hope my answer clarifies the confusion. 

Thanks for the review and the detailed replies.

**Comment by liamcain** [comment]
Okay, sounds like the behavior is intended.
