### ISSUE TITLE
Cant seem to find the command to create timeline

### ISSUE THREAD

**Issue by dummifiedme** [Darakah/obsidian-timelines#10]
Ctrl+P doesnt show any command "create timeline" 
![image](https://user-images.githubusercontent.com/68785729/111758942-178c4100-88c3-11eb-94af-401b057e3689.png)

**Comment by Darakah** [comment]
Please check the README

<img width="862" alt="Screen Shot 2021-03-19 at 10 41 41 AM" src="https://user-images.githubusercontent.com/29651407/111761042-b7d06e80-889f-11eb-8be2-a0e8317d4a5e.png">

**Comment by dummifiedme** [comment]
How to use the render block?

PS. I followed the readme given on the[ link on the Plugin Info page](https://github.com/Darakah/obsidian-timelines/issues/2). Kindly remove the link if it's not valid now :)

Thanks

**Comment by dummifiedme** [comment]
I tried adding the render block, didn't work for me.

I should basically arrange all the notes with the tags specified and the class tags right?

**Comment by Darakah** [comment]
The link explanation about tag filters and how to search is still valid the only difference is that instead of using a command you use the render block.

What `class tags` are you referring to? the only thing you need to provide are the tags (same as with the command)
So to show a timeline for all files with the tag `#here`

you just write:

<img width="175" alt="Screen Shot 2021-03-19 at 11 40 22 AM" src="https://user-images.githubusercontent.com/29651407/111768186-e7837480-88a7-11eb-9eb7-bb621ed88510.png">

**Comment by dummifiedme** [comment]
> What `class tags` are you referring to?
This: 
`<span class='ob-timelines' data-date='1444-10-00-00' data-title='TITLE' data-img = 'https://i.pinimg.com/564x/03/b2/12/03b2128a911d9a8168189201b358a8d0.jpg'> D E S C R  </span>`

**Comment by Darakah** [comment]
does the note have the `#timeline` tag ?

**Comment by dummifiedme** [comment]
Yes.

I created two notes like this for testing

![image](https://user-images.githubusercontent.com/68785729/111769195-eca7ea00-88ce-11eb-9942-5ffd6a766035.png)

Then in another note, wrote this:
![image](https://user-images.githubusercontent.com/68785729/111769245-fdf0f680-88ce-11eb-9c92-84d4b3e1ee8f.png)

**Comment by Darakah** [comment]
why is your data-title='TITLE'2 <---- ??

**Comment by dummifiedme** [comment]
Yeah, sorry, I fixed it. (typo)

![image](https://user-images.githubusercontent.com/68785729/111769620-735cc700-88cf-11eb-8c00-3fe1f17644e3.png)

**Comment by Darakah** [comment]
@dummifiedme 

Do you have this in your yaml? can you add it?

<img width="178" alt="Screen Shot 2021-03-19 at 11 58 24 AM" src="https://user-images.githubusercontent.com/29651407/111770210-69749d00-88aa-11eb-82da-26c565ccbc56.png">

**Comment by dummifiedme** [comment]
> 
> 
> @dummifiedme
> 
> Do you have this in your yaml? can you add it?
> 
> <img alt="Screen Shot 2021-03-19 at 11 58 24 AM" width="178" src="https://user-images.githubusercontent.com/29651407/111770210-69749d00-88aa-11eb-82da-26c565ccbc56.png">

I tried with YAML and without it as well. Both doesnt work,

BTW, timeline tag has to be a part of YAML or it should work if note has that tag anywhere on the note?

**Comment by Darakah** [comment]
Question, are you clicking on another note and back to this note after you added the YAML? 
the render block will not update otherwise.

Yes, the timeline tag has to be in YAML for current version, other tags can be wherever

**Comment by dummifiedme** [comment]
Got it to work. Thanks. 
With timeline in YAML and other tag in the text, it rendered correctly.

**Comment by Darakah** [comment]
@dummifiedme so the problem was you didn't reopen the note to re-render the block?

what do you mean by clean new page? can you clarify? 
wherever you put the block the timeline will be created there, it can be in an empty note or inside another note with other stuff / text

**Comment by Darakah** [comment]
Also, if you think you can explain how to use better in the README, feel free to push a pull request for it or send here and I will update it.

**Comment by dummifiedme** [comment]
> @dummifiedme so the problem was you didn't reopen the note to re-render the block?

Yes, I think.

> what do you mean by clean new page? can you clarify?
> wherever you put the block the timeline will be created there, it can be in an empty note or inside another note with other stuff / text

For me it works only on a new page.
It is not rendering anything on a page with some text above it.

**Comment by Darakah** [comment]
@dummifiedme its most likely being placed behind the text, check positioning / margin for the block or the text.  
<img width="931" alt="Screen Shot 2021-03-19 at 12 37 47 PM" src="https://user-images.githubusercontent.com/29651407/111774555-ea826300-88af-11eb-95ed-7bd23e2b450b.png">

**Comment by dummifiedme** [comment]
Yes, my bad. I just had to refresh the page and check for alignment.

Thanks for all the help :)
