### ISSUE TITLE
Having the option to sort the timeline asc/desc

### ISSUE THREAD

**Issue by timtreis** [Darakah/obsidian-timelines#12]
It would be nice to have the most recent event be at the top of the list.

**Comment by Darakah** [comment]
<img width="1118" alt="Screen Shot 2021-04-03 at 6 34 05 PM" src="https://user-images.githubusercontent.com/29651407/113484911-2cfc9000-94ab-11eb-9173-e01b2f9152d5.png">

**Comment by timtreis** [comment]
Oh, thanks a lot! Maybe this could then also be documented in the doc :) Great plugin!
