### ISSUE TITLE
Spacing proportional to time

### ISSUE THREAD

**Issue by xplosionmind** [Darakah/obsidian-timelines#8]
It would be awesome if the distance among timeline events could be proportional to the amount of time passed from one to the other. Obviously, since the timeline may have “holes” where there are no events for a long time, it would be really important to easily zoom in and out.

**Comment by Darakah** [comment]
The holes are not the main problem per say but the cards display. The size of a card varies greatly as it is user defined (if there is img, size of the descriptions and most importantly how many events at that 1 date). 

As currently elements are first sorted and then displayed sequential this can be ignored. 

So, to make this happen first all events at 1 time must be collapsed and expended on user click. Second "holed" (which can be extremly long sometime) also expendable on user click and reprsented by a // in the middle of the timeline for example. 

Gonna be a bit further down the road for this one.
If you have any fancy / easy way of implementing it feel free to push a PR

**Comment by Darakah** [comment]
Added in version `0.3.0` through `timeline-vis` block in horizontal view
